trigger LeadTrigger16 on Lead (after insert) {
    //Example 16: When a lead is inserted, create a task for lead record...
    //and create another lead through trigger.....
    
    List<Task> taskList = new List<Task>();
    
    for(Lead w : Trigger.new){
        Task tobj = new Task(Subject = 'A new lead record is inserted, please contact with the lead!', WhoId = w.Id);
        
        taskList.add(tobj);
    }
    insert taskList;
    
    //do the rest in handler.....
    
    LeadTrigger16Handler.afterInsertHandlerLead(Trigger.new);
}
//recursion: some kind of endless repetition in execution....
//Avoding recursion is important:...
//We will learn how to avoid endless repetition...
//I want to execute my trigger only once...
//After trigger codes executed completely, I will lock the for recursion....